# Generated by Django 4.1.3 on 2022-11-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PreEntrega", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductosM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=15)),
                ("precio", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductosN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=15)),
                ("precio", models.IntegerField()),
            ],
        ),
        migrations.RenameModel(old_name="Productos", new_name="ProductosH",),
    ]
