# Generated by Django 4.1.3 on 2022-11-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PreEntrega", "0002_productosm_productosn_rename_productos_productosh"),
    ]

    operations = [
        migrations.AddField(
            model_name="productosh",
            name="imagen",
            field=models.ImageField(null=True, upload_to="productos"),
        ),
        migrations.AddField(
            model_name="productosm",
            name="imagen",
            field=models.ImageField(null=True, upload_to="productos"),
        ),
        migrations.AddField(
            model_name="productosn",
            name="imagen",
            field=models.ImageField(null=True, upload_to="productos"),
        ),
    ]
